"""Ajout pays et frais dans Retrait

Revision ID: 0bdec54d70da
Revises: 128e88d180a1
Create Date: 2026-01-13 20:07:23.477056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdec54d70da'
down_revision = '128e88d180a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pays', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('frais', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.drop_column('frais')
        batch_op.drop_column('pays')

    # ### end Alembic commands ###
