"""Fix parrainage with parrain_id

Revision ID: 21a140b940b8
Revises: 7832273eea6a
Create Date: 2026-01-09 13:36:55.794664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a140b940b8'
down_revision = '7832273eea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parrain_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_parrain_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['parrain_id'], ['id'])
        batch_op.drop_column('parrain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parrain', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_parrain_fkey'), 'user', ['parrain'], ['username'])
        batch_op.drop_column('parrain_id')

    # ### end Alembic commands ###
