"""empty message

Revision ID: 234aef6c4bdc
Revises: f7e43bc5eedb
Create Date: 2026-01-23 10:30:09.819384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234aef6c4bdc'
down_revision = 'f7e43bc5eedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
