"""ajout

Revision ID: 2fa286174a56
Revises: 9f6ce3844e09
Create Date: 2026-01-10 19:34:35.058113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa286174a56'
down_revision = '9f6ce3844e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrait_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_utilises', sa.Integer(), nullable=False),
    sa.Column('montant_xof', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_spun', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_spun')

    op.drop_table('retrait_points')
    # ### end Alembic commands ###
