"""parrain uses username

Revision ID: 7832273eea6a
Revises: 4b8f6d9da568
Create Date: 2026-01-09 13:06:56.825218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7832273eea6a'
down_revision = '4b8f6d9da568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_parrain_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['parrain'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_parrain_fkey'), 'user', ['parrain'], ['uid'])

    # ### end Alembic commands ###
