"""ajout

Revision ID: 887d6e466d48
Revises: 0bdec54d70da
Create Date: 2026-01-14 12:49:43.782189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887d6e466d48'
down_revision = '0bdec54d70da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_youtube_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_youtube_date')

    # ### end Alembic commands ###
