"""add user_id to retrait

Revision ID: 8e58d9cc9b5d
Revises: c53381caed41
Create Date: 2026-03-18 13:56:18.633982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e58d9cc9b5d'
down_revision = 'c53381caed41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_name'], ['username'], ondelete='CASCADE')

    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
