"""Fix parrainage with parrain_id

Revision ID: 9f6ce3844e09
Revises: 21a140b940b8
Create Date: 2026-01-09 15:54:31.101733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6ce3844e09'
down_revision = '21a140b940b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parrain', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_parrain_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['parrain'], ['username'])
        batch_op.drop_column('parrain_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parrain_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_parrain_id_fkey'), 'user', ['parrain_id'], ['id'])
        batch_op.drop_column('parrain')

    # ### end Alembic commands ###
