"""Add has_spun_wheel to User

Revision ID: bb9ca21828d9
Revises: 2fa286174a56
Create Date: 2026-01-10 19:57:11.875845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9ca21828d9'
down_revision = '2fa286174a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_spun_wheel', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_spun_wheel')

    # ### end Alembic commands ###
